### ISSUE TITLE
How to access the read file values in a python array / list

### ISSUE THREAD

**Issue by Jeevantk** [jove1/ae#1]
I wanted to access the data read from the wfs file to be accessed in a python variable so that I can do additional processing on that. I havent found any documentation regarding that .

**Comment by jove1** [comment]
```
import ae
f = ae.open("file.wfs")
for i,data in f.iter_blocks(progress=ae.no_progress):
    print i, data
```
shape of data may be awkward due to the different storage block sizes in different file formats, you can just flatten it

**Comment by Jeevantk** [comment]
Thank a lot
